// frontend/src/components/layout/Header/Header.tsx
import React, { useState, useEffect } from 'react';
import { Link, NavLink } from 'react-router-dom';
import './Header.scss';

const Header: React.FC = () => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 10);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navItems = [
    { label: 'Home', path: '/' },
    { label: 'Explore', path: '/explore' },
    { label: 'My Collection', path: '/collection' },
    { label: 'Wishlist', path: '/wishlist' },
    { label: 'Dashboard', path: '/dashboard' },
  ];

  return (
    <header className={`header${scrolled ? ' header--scrolled' : ''}`}>
      <div className="header__inner">
        <Link to="/" className="header__logo" onClick={() => setMobileMenuOpen(false)}>
          <span className="header__logo-icon">🎮</span>
          <span className="header__logo-text">RetroTracker</span>
        </Link>

        <nav className={`header__nav${mobileMenuOpen ? ' header__nav--open' : ''}`}>
          {navItems.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              end={item.path === '/'}
              className={({ isActive }) =>
                `header__link${isActive ? ' active' : ''}`
              }
              onClick={() => setMobileMenuOpen(false)}
            >
              {item.label}
            </NavLink>
          ))}
        </nav>

        <div className="header__actions">
          <Link to="/login" className="header__link header__link--auth">Sign In</Link>
          <Link to="/register" className="header__cta">Sign Up</Link>
          <button
            className={`header__menu-btn${mobileMenuOpen ? ' header__menu-btn--open' : ''}`}
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle menu"
          >
            <span /><span /><span />
          </button>
        </div>
      </div>
      {mobileMenuOpen && <div className="header__overlay" onClick={() => setMobileMenuOpen(false)} />}
    </header>
  );
};

export default Header;

// frontend/src/app/shared/components/header/header.component.ts
import { Component, HostListener } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  mobileMenuOpen = false;
  scrolled = false;

  @HostListener('window:scroll')
  onScroll(): void {
    this.scrolled = window.scrollY > 10;
  }

  toggleMobileMenu(): void {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  closeMobileMenu(): void {
    this.mobileMenuOpen = false;
  }

  navItems = [
    { label: 'Home', path: '/' },
    { label: 'Explore', path: '/explore' },
    { label: 'My Collection', path: '/collection' },
    { label: 'Wishlist', path: '/wishlist' },
    { label: 'Dashboard', path: '/dashboard' },
  ];
}

<header class="header" [class.header--scrolled]="scrolled">
  <div class="header__inner">
    <a routerLink="/" class="header__logo" (click)="closeMobileMenu()">
      <span class="header__logo-icon">🎮</span>
      <span class="header__logo-text">RetroTracker</span>
    </a>

    <nav class="header__nav" [class.header__nav--open]="mobileMenuOpen">
      @for (item of navItems; track item.path) {
        <a
          [routerLink]="item.path"
          routerLinkActive="active"
          [routerLinkActiveOptions]="{ exact: item.path === '/' }"
          class="header__link"
          (click)="closeMobileMenu()"
        >
          {{ item.label }}
        </a>
      }
    </nav>

    <div class="header__actions">
      <a routerLink="/login" class="header__link header__link--auth">Sign In</a>
      <a routerLink="/register" class="header__cta">Sign Up</a>
      <button
        class="header__menu-btn"
        [class.header__menu-btn--open]="mobileMenuOpen"
        (click)="toggleMobileMenu()"
        aria-label="Toggle menu"
      >
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </div>
</header>

@if (mobileMenuOpen) {
  <div class="header__overlay" (click)="closeMobileMenu()"></div>
}
