// frontend/src/app/shared/components/badge/badge.component.ts
import { Component, Input } from '@angular/core';

export type BadgeVariant = 'success' | 'warning' | 'danger' | 'info' | 'default' | 'highlight';

@Component({
  selector: 'app-badge',
  standalone: true,
  template: `
    <span class="badge badge--{{ variant }}">
      <ng-content />
    </span>
  `,
  styleUrls: ['./badge.component.scss'],
})
export class BadgeComponent {
  @Input() variant: BadgeVariant = 'default';
}

// frontend/src/components/ui/Badge/Badge.tsx
import React from 'react';
import './Badge.scss';

interface BadgeProps {
  variant?: 'success' | 'warning' | 'danger' | 'info' | 'default' | 'highlight';
  children: React.ReactNode;
}

const Badge: React.FC<BadgeProps> = ({ variant = 'default', children }) => {
  return <span className={`badge badge--${variant}`}>{children}</span>;
};

export default Badge;
