// frontend/src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    <footer class="footer">
      <div class="footer__inner">
        <div class="footer__brand">
          <span class="footer__logo">🎮 RetroTracker</span>
          <p class="footer__tagline">Your retro gaming collection, beautifully organized.</p>
        </div>
        <div class="footer__links">
          <a routerLink="/explore">Explore</a>
          <a routerLink="/collection">My Collection</a>
          <a routerLink="/wishlist">Wishlist</a>
          <a routerLink="/dashboard">Dashboard</a>
        </div>
        <div class="footer__bottom">
          <p>&copy; {{ year }} Retro Collection Tracker. All rights reserved.</p>
        </div>
      </div>
    </footer>
  `,
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  year = new Date().getFullYear();
}

// frontend/src/components/layout/Footer/Footer.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import './Footer.scss';

const Footer: React.FC = () => {
  const year = new Date().getFullYear();

  return (
    <footer className="footer">
      <div className="footer__inner">
        <div className="footer__brand">
          <span className="footer__logo">🎮 RetroTracker</span>
          <p className="footer__tagline">Your retro gaming collection, beautifully organized.</p>
        </div>
        <div className="footer__links">
          <Link to="/explore">Explore</Link>
          <Link to="/collection">My Collection</Link>
          <Link to="/wishlist">Wishlist</Link>
          <Link to="/dashboard">Dashboard</Link>
        </div>
        <div className="footer__bottom">
          <p>&copy; {year} Retro Collection Tracker. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
