// frontend/src/app/features/login/login.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { InputComponent } from '../../shared/components/input/input.component';
import { ButtonComponent } from '../../shared/components/button/button.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [RouterLink, InputComponent, ButtonComponent],
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <h1 class="auth-card__title">Welcome Back</h1>
        <p class="auth-card__subtitle">Sign in to your collection</p>

        <form class="auth-card__form" (submit)="$event.preventDefault()">
          <app-input
            label="Email"
            type="email"
            placeholder="you@example.com"
            [required]="true"
          ></app-input>
          <app-input
            label="Password"
            type="password"
            placeholder="Your password"
            [required]="true"
          ></app-input>
          <app-button type="submit" variant="primary" class="auth-card__submit">
            Sign In
          </app-button>
        </form>

        <p class="auth-card__footer">
          Don't have an account? <a routerLink="/register">Create one</a>
        </p>
      </div>
    </div>
  `,
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {}

// frontend/src/pages/Login/Login.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import Input from '../../components/ui/Input/Input';
import Button from '../../components/ui/Button/Button';
import './Login.scss';

const Login: React.FC = () => {
  return (
    <div className="auth-page">
      <div className="auth-card">
        <h1 className="auth-card__title">Welcome Back</h1>
        <p className="auth-card__subtitle">Sign in to your collection</p>
        <form className="auth-card__form" onSubmit={(e) => e.preventDefault()}>
          <Input label="Email" type="email" placeholder="you@example.com" required />
          <Input label="Password" type="password" placeholder="Your password" required />
          <Button type="submit" variant="primary">Sign In</Button>
        </form>
        <p className="auth-card__footer">
          Don't have an account? <Link to="/register">Create one</Link>
        </p>
      </div>
    </div>
  );
};

export default Login;
