// frontend/src/app/shared/components/alert/alert.component.ts
import { Component, Input } from '@angular/core';

export type AlertVariant = 'success' | 'warning' | 'danger' | 'info';

@Component({
  selector: 'app-alert',
  standalone: true,
  template: `
    <div class="alert alert--{{ variant }}" role="alert" [class.alert--dismissible]="dismissible">
      @if (icon) {
        <span class="alert__icon">{{ icon }}</span>
      }
      <div class="alert__content">
        @if (title) {
          <strong class="alert__title">{{ title }}</strong>
        }
        <p class="alert__message"><ng-content /></p>
      </div>
    </div>
  `,
  styleUrls: ['./alert.component.scss'],
})
export class AlertComponent {
  @Input() variant: AlertVariant = 'info';
  @Input() title?: string;
  @Input() icon?: string;
  @Input() dismissible = false;
}

// frontend/src/components/ui/Alert/Alert.tsx
import React from 'react';
import './Alert.scss';

interface AlertProps {
  variant?: 'success' | 'warning' | 'danger' | 'info';
  title?: string;
  icon?: string;
  children: React.ReactNode;
}

const Alert: React.FC<AlertProps> = ({ variant = 'info', title, icon, children }) => {
  return (
    <div className={`alert alert--${variant}`} role="alert">
      {icon && <span className="alert__icon">{icon}</span>}
      <div className="alert__content">
        {title && <strong className="alert__title">{title}</strong>}
        <p className="alert__message">{children}</p>
      </div>
    </div>
  );
};

export default Alert;
