// frontend/src/app/shared/components/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  template: `
    <div class="loading-spinner" [class.loading-spinner--full]="fullPage">
      <div class="loading-spinner__ring"></div>
      @if (message) {
        <p class="loading-spinner__message">{{ message }}</p>
      }
    </div>
  `,
  styleUrls: ['./loading-spinner.component.scss'],
})
export class LoadingSpinnerComponent {
  @Input() message = 'Loading...';
  @Input() fullPage = false;
}

// frontend/src/components/ui/LoadingSpinner/LoadingSpinner.tsx
import React from 'react';
import './LoadingSpinner.scss';

interface LoadingSpinnerProps {
  message?: string;
  fullPage?: boolean;
}

const LoadingSpinner: React.FC<LoadingSpinnerProps> = ({
  message = 'Loading...',
  fullPage = false,
}) => {
  return (
    <div className={`loading-spinner${fullPage ? ' loading-spinner--full' : ''}`}>
      <div className="loading-spinner__ring" />
      {message && <p className="loading-spinner__message">{message}</p>}
    </div>
  );
};

export default LoadingSpinner;
